# Gaming Workforce Observatory - Secrets Template
# Renommez ce fichier en 'secrets.toml' et configurez vos clés

[database]
# Configuration base de données (si applicable)
# connection_string = "postgresql://user:password@localhost:5432/workforce_db"
# username = "your_db_username"
# password = "your_db_password"

[external_apis]
# Clés API externes (si applicable) 
# hr_system_api_key = "your_hr_api_key"
# slack_webhook = "https://hooks.slack.com/your_webhook"

[authentication]
# Configuration authentification (si applicable)
# secret_key = "your_secret_key_for_sessions"
# admin_password = "your_admin_password"

[performance]
# Configuration performance
cache_ttl = 300  # Cache TTL en secondes (5 minutes)
max_data_rows = 10000  # Limite nombre de lignes

[features]
# Feature flags
enable_ml_predictions = true
enable_advanced_analytics = true
enable_export_features = true
